apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-deployment
  template:
    metadata:
      labels:
        app: springboot-deployment
    spec:
      containers:
        - name: maven-joe-recent
          image: jothishivani/maven-recent:latest
          ports:
            - containerPort: 8084
